name:        'Get Changed Files'
description: 'Saves lists of changed files as JSON for use by other actions.'
author:      'Dustin Falgout <dustin@falgout.us>'
runs:
  using: 'node12'
  main:  'dist/main.js'
inputs:
  token:
    description: GitHub Personal Access Token
    required:    true
outputs:
  all:
    description: Array of all changed files (JSON string)
  added:
    description: Array of added files (JSON string)
  deleted:
    description: Array of deleted files (JSON string)
  modified:
    description: Array of modified files (JSON string)
  renamed:
    description: Array of renamed files (JSON string)
branding:
  icon:  'search'
  color: 'gray-dark'
