name: action-build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next
    paths-ignore:
      - "dist/**"
      - "README.md"
      - CHANGELOG.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install Packages
        run: yarn install
      - run: yarn build
      - name: Release
        run: yarn semantic-release
